src/Entity/Colors.php
<?php

namespace App\Entity;

use App\Repository\ColorsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ColorsRepository::class)
 */
class Colors
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $bg_name;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $text_name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $btn_name;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $btn_outline_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bg_light_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $border_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $turkish_name;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="banner_color_id")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=ContactType::class, mappedBy="color")
     */
    private $contactTypes;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->contactTypes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBgName(): ?string
    {
        return $this->bg_name;
    }

    public function setBgName(?string $bg_name): self
    {
        $this->bg_name = $bg_name;

        return $this;
    }

    public function getTextName(): ?string
    {
        return $this->text_name;
    }

    public function setTextName(?string $text_name): self
    {
        $this->text_name = $text_name;

        return $this;
    }

    public function getBtnName(): ?string
    {
        return $this->btn_name;
    }

    public function setBtnName(?string $btn_name): self
    {
        $this->btn_name = $btn_name;

        return $this;
    }

    public function getBtnOutlineName(): ?string
    {
        return $this->btn_outline_name;
    }

    public function setBtnOutlineName(?string $btn_outline_name): self
    {
        $this->btn_outline_name = $btn_outline_name;

        return $this;
    }

    public function getBgLightName(): ?string
    {
        return $this->bg_light_name;
    }

    public function setBgLightName(?string $bg_light_name): self
    {
        $this->bg_light_name = $bg_light_name;

        return $this;
    }

    public function getBorderName(): ?string
    {
        return $this->border_name;
    }

    public function setBorderName(?string $border_name): self
    {
        $this->border_name = $border_name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTurkishName(): ?string
    {
        return $this->turkish_name;
    }

    public function setTurkishName(string $turkish_name): self
    {
        $this->turkish_name = $turkish_name;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setBannerColor($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getBannerColor() === $this) {
                $user->setBannerColor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ContactType[]
     */
    public function getContactTypes(): Collection
    {
        return $this->contactTypes;
    }

    public function addContactType(ContactType $contactType): self
    {
        if (!$this->contactTypes->contains($contactType)) {
            $this->contactTypes[] = $contactType;
            $contactType->setColor($this);
        }

        return $this;
    }

    public function removeContactType(ContactType $contactType): self
    {
        if ($this->contactTypes->removeElement($contactType)) {
            // set the owning side to null (unless already changed)
            if ($contactType->getColor() === $this) {
                $contactType->setColor(null);
            }
        }

        return $this;
    }
}

src/Entity/General.php
<?php

namespace App\Entity;

use App\Repository\GeneralRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GeneralRepository::class)
 * @ORM\Table(name="`general`")
 */
class General
{

    CONST GLOBAL = 1;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $instagram;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $youtube;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categoryName;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_slider;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $siteUrl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $serviceName;

    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private $headCode;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_googletag;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $headCss;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isReturnPhoneForAds;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(string $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getCategoryName(): ?string
    {
        return $this->categoryName;
    }

    public function setCategoryName(string $categoryName): self
    {
        $this->categoryName = $categoryName;

        return $this;
    }

    public function getIsSlider(): ?bool
    {
        return $this->is_slider;
    }

    public function setIsSlider(?bool $is_slider): self
    {
        $this->is_slider = $is_slider;

        return $this;
    }

    public function getSiteUrl(): ?string
    {
        return $this->siteUrl;
    }

    public function setSiteUrl(?string $siteUrl): self
    {
        $this->siteUrl = $siteUrl;

        return $this;
    }

    public function getServiceName(): ?string
    {
        return $this->serviceName;
    }

    public function setServiceName(?string $serviceName): self
    {
        $this->serviceName = $serviceName;

        return $this;
    }

    public function getHeadCode(): ?string
    {
        return $this->headCode;
    }

    public function setHeadCode(?string $headCode): self
    {
        $this->headCode = $headCode;

        return $this;
    }

    public function getIsGoogletag(): ?bool
    {
        return $this->is_googletag;
    }

    public function setIsGoogletag(?bool $is_googletag): self
    {
        $this->is_googletag = $is_googletag;

        return $this;
    }

    public function getHeadCss(): ?string
    {
        return $this->headCss;
    }

    public function setHeadCss(?string $headCss): self
    {
        $this->headCss = $headCss;

        return $this;
    }

    public function getIsReturnPhoneForAds(): ?bool
    {
        return $this->isReturnPhoneForAds;
    }

    public function setIsReturnPhoneForAds(?bool $isReturnPhoneForAds): self
    {
        $this->isReturnPhoneForAds = $isReturnPhoneForAds;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Category;
use App\Entity\Corporate;
use App\Entity\Phone;
use App\Entity\Slider;
use App\Entity\UserComment;
use App\Entity\UserLog;
use App\Generator\GlobalGenerator;
use App\Service\SmsService;
use App\Service\UserLogService;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{

    /**
     * @var EntityManagerInterface
     */
    private EntityManagerInterface $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/", name="home")
     * @Template()
     */
    public function index(UserLogService $userLogService, Request $request, GlobalGenerator $globalGenerator)
    {
        /** @var Corporate $corporateIndex */
        $corporateIndex = $this->em->getRepository(Corporate::class)->findOneBy(['is_index' => true]);
        /** @var Slider $sliders */
        $sliders = $this->em->getRepository(Slider::class)->findBy([], ['queue' => 'ASC']);
        /** @var Phone $phone */
        $phone = $this->em->getRepository(Phone::class)->find(1);
        /** @var Category $category */
        $category = $this->em->getRepository(Category::class)->findAll();

        $blogs = $this->em->getRepository(Blog::class)->findAll();

        return [
            'sliders' => $sliders,
            'phone' => $phone,
            'corporateIndex' => $corporateIndex,
            'categorys' => $category,
            'blogs' => $blogs
        ];
    }


    /**
     * @Route("/check-ads", name="check_ads")
     */
    public function checkAds(UserLogService $userLogService, Request $request, SmsService $smsService): Response
    {
        $userLogService->userLogControl($request);
        /** @var Corporate $corporateIndex */
        $corporateIndex = $this->em->getRepository(Corporate::class)->findOneBy(['is_index' => true]);
        /** @var Slider $sliders */
        $sliders = $this->em->getRepository(Slider::class)->findBy([], ['queue' => 'ASC']);
        /** @var Phone $phone */
        $phone = $this->em->getRepository(Phone::class)->find(1);
        /** @var Category $category */
        $category = $this->em->getRepository(Category::class)->findAll();

        $blogs = $this->em->getRepository(Blog::class)->findAll();

        return $this->render('home/index.html.twig',[
            'sliders' => $sliders,
            'phone' => $phone,
            'corporateIndex' => $corporateIndex,
            'categorys' => $category,
            'blogs' => $blogs
        ]);
    }
}

templates/home/contact_index_normal.html.twig
{% if district is defined %}
    {% if district.contact %}
        <a class="text-center btn {{ district.contact.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ district.contact.type.value.value }}{{ district.contact.value }}');" {% endif%} href="{{ district.contact.type.value.value }}{{ district.contact.value }}">{{ district.contact.title }} <i class="{{ district.contact.type.value.icon }}"></i></a>

        <a class="text-center btn {{ global.contactWhatsApp.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ global.contactWhatsApp.type.value.value }}{{ global.contactWhatsApp.value }}');" {% endif%} href="{{ global.contactWhatsApp.type.value.value }}{{ global.contactWhatsApp.value }}">{{ global.contactWhatsApp.title }} <i class="{{ global.contactWhatsApp.type.value.icon }}"></i></a>
    {% else %}
        {% for contact in global.contactIndex %}
            <a class="text-center btn {{ contact.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ contact.type.value.value }}{{ contact.value }}');" {% endif%} href="{{ contact.type.value.value }}{{ contact.value }}">{{ contact.title }} <i class="{{ contact.type.value.icon }}"></i></a>
        {% endfor %}
    {% endif %}
{% else %}
    {% if neighborhood is defined %}
        {% if neighborhood.district.contact %}
            <a class="text-center btn {{ neighborhood.district.contact.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ neighborhood.district.contact.type.value.value }}{{ neighborhood.district.contact.value }}');" {% endif%} href="{{ neighborhood.district.contact.type.value.value }}{{ neighborhood.district.contact.value }}">{{ neighborhood.district.contact.title }} <i class="{{ neighborhood.district.contact.type.value.icon }}"></i></a>

            <a class="text-center btn {{ global.contactWhatsApp.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ global.contactWhatsApp.type.value.value }}{{ global.contactWhatsApp.value }}');" {% endif%} href="{{ global.contactWhatsApp.type.value.value }}{{ global.contactWhatsApp.value }}">{{ global.contactWhatsApp.title }} <i class="{{ global.contactWhatsApp.type.value.icon }}"></i></a>
        {% else %}
            {% for contact in global.contactIndex %}
                <a class="text-center btn {{ contact.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ contact.type.value.value }}{{ contact.value }}');" {% endif%} href="{{ contact.type.value.value }}{{ contact.value }}">{{ contact.title }} <i class="{{ contact.type.value.icon }}"></i></a>
            {% endfor %}
        {% endif %}
    {% else %}
        {% for contact in global.contactIndex %}
            <a class="text-center btn {{ contact.type.color.btnName }}" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ contact.type.value.value }}{{ contact.value }}');" {% endif%} href="{{ contact.type.value.value }}{{ contact.value }}">{{ contact.title }} <i class="{{ contact.type.value.icon }}"></i></a>
        {% endfor %}
    {% endif %}
{% endif %}

templates/home/contact_sidebar.html.twig
<div style="position:fixed; z-index:998; bottom: 1px; right: 1px;">
    {% for contact in global.contactSidebar %}
        <a class="btn-floating btn-lg btn-large {{ contact.type.color.btnName }} waves-effect" {% if global.general.isGoogletag %}
            onclick="return gtag_report_conversion('{{ contact.type.value.value }}{{ contact.value }}');" {% endif%}
           href="{{ contact.type.value.value }}{{ contact.value }}">
            <i class="{{ contact.type.value.icon }}"></i>
        </a>
        {% if loop.index != loop.last %}
            <br>
        {% endif %}
    {% endfor %}
</div>

templates/home/header.html.twig
<!-- Navigation & Intro -->
{% if global.isSlider %}
    {% block stylesheets %}
        <style>
            html,
            body,
            header,
            .view {
                height: 100%;
            }
            @media (min-width: 451px) and (max-width: 740px) {
                html,
                body,
                header,
                .view {
                    height: 500px;
                }
            }
            @media (min-width: 800px) and (max-width: 850px) {
                html,
                body,
                header,
                .view {
                    height: 550px;
                }
            }

            /* Carousel*/
            .carousel,
            .carousel-item,
            .carousel-item.active {
                height: 100%;
            }

            .carousel-inner {
                height: 100%;
            }
            {% if category.slider is defined and category.slider is not null %}
                .carousel-item:nth-child(1) {
                    background-image: url("{{ category.slider.photo }}");
                    background-repeat: no-repeat;
                    background-size: cover;
                    background-attachment: fixed;
                    background-position: center center;
                }
            {% elseif cityWithCategory.category.slider is defined and cityWithCategory.category.slider is not null %}
            .carousel-item:nth-child(1) {
                background-image: url("{{ cityWithCategory.category.slider.photo }}");
                background-repeat: no-repeat;
                background-size: cover;
                background-attachment: fixed;
                background-position: center center;
            }
            {% else %}
                {% for sPhoto in global.slider %}
                .carousel-item:nth-child({{ loop.index }}) {
                    background-image: url("{{ sPhoto.photo }}");
                    background-repeat: no-repeat;
                    background-size: cover;
                    background-attachment: fixed;
                    background-position: center center;
                }
                {% endfor %}
            {% endif %}
        </style>
    {% endblock %}
{% endif %}

<header>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top scrolling-navbar white">
        <div class="container-fluid">
            <a class="navbar-brand font-weight-bold title" href="{{ path('home') }}">{{ global.name }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="list-unstyled navbar-nav mx-auto">
                    <li class="nav-item ml-4">
                        <a class="nav-link title" href="{{ path('home') }}" data-offset="90">Ana sayfa</a>
                    </li>
                    <li class="nav-item dropdown ml-4 mb-0">
                        <a class="nav-link dropdown-toggle title" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false"> Hizmetler </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for c in global.category %}
                                <a class="dropdown-item" href="{{ path('category', {'categorySlug':c.slug}) }}">{{ c.title }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item dropdown ml-4 mb-0">
                        <a class="nav-link dropdown-toggle title" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false"> Kurumsal </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for corporate in global.corporate %}
                                <a class="dropdown-item" href="{{ path('corporate', {'corporateSlug':corporate.slug}) }}">{{ corporate.title }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item dropdown ml-4 mb-0">
                        <a class="nav-link dropdown-toggle title" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false"> Blog </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for blog in global.blog %}
                                <a class="dropdown-item" href="{{ path('blog', {'blogSlug':blog.slug}) }}">{{ blog.title }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item ml-4">
                        <a class="nav-link title" href="{{ path('faq') }}" data-offset="90">S.S.S</a>
                    </li>
                    <li class="nav-item ml-4">
                        <a class="nav-link title" href="{{ path('comment') }}" data-offset="90">Yorumlar</a>
                    </li>
                </ul>
                <!-- Social Icon  -->
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ global.general.facebook }}" target="_blank">
                            <i class="fab fa-facebook-f title"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ global.general.twitter }}" target="_blank">
                            <i class="fab fa-twitter title"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ global.general.youtube }}" target="_blank">
                            <i class="fab fa-youtube title"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ global.general.instagram }}" target="_blank">
                            <i class="fab fa-instagram title"></i>
                        </a>
                    </li>
                    <li class="nav-item ml-3">
                        <a class="btn {{ global.contactFixed.type.color.btnName }} text-white btn-rounded btn-sm font-weight-bold" {% if global.general.isGoogletag %} onclick="return gtag_report_conversion('{{ global.contactFixed.type.value.value }}{{ global.contactFixed.value }}');" {% endif%} href="tel:{{ global.contactFixed.type.value.value }}{{ global.contactFixed.value }}" data-offset="90">{{ global.contactFixed.title }}</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% if global.isSlider %}
        <!-- Carousel Wrapper -->
        <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">

            <!-- Indicators -->
            <ol class="carousel-indicators">
                {% if category.slider is defined and category.slider is not null %}

                        <li data-target="#carousel" data-slide-to="{{ category.slider.queue }}" class="active">
                        </li>

                {% elseif cityWithCategory.category.slider is defined and cityWithCategory.category.slider is not null %}
                    <li data-target="#carousel" data-slide-to="{{ cityWithCategory.category.slider.queue }}" class="active">
                    </li>
                {% else %}
                    {% for slider in global.slider %}
                        <li data-target="#carousel" data-slide-to="{{ slider.queue }}"
                                {% if loop.index == 1 %}
                                    class="active"
                                {% endif %}
                        >
                        </li>
                    {% endfor %}
                {% endif %}
            </ol>
            <!-- Indicators -->

            <!-- Slides -->
            <div class="carousel-inner" role="listbox">
                {% if category.slider is defined and category.slider is not null %}
                    <div class="carousel-item active">
                        <!-- Mask -->
                        <div class="view">
                            <div
                                    class="h-100 d-flex justify-content-center align-items-center mask rgba-black-light white-text text-center">
                                <ul class="list-unstyled animated fadeInUp col-md-12">
                                    <li>
                                        <h1 class="display-6 font-weight-bold wow fadeIn" data-wow-delay="0.3s">{{ category.slider.title }}</h1>
                                        <hr class="hr-light wow fadeIn w-50" data-wow-delay="0.3s">
                                    </li>
                                    <li>
                                        <h3>{{ category.slider.description }}</h3>
                                    </li>
                                    <li>
                                        {% include 'home/contact_index_normal.html.twig' %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Mask -->
                    </div>
                {% elseif cityWithCategory.category.slider is defined and cityWithCategory.category.slider is not null %}
                    <div class="carousel-item active">
                        <!-- Mask -->
                        <div class="view">
                            <div
                                    class="h-100 d-flex justify-content-center align-items-center mask rgba-black-light white-text text-center">
                                <ul class="list-unstyled animated fadeInUp col-md-12">
                                    <li>
                                        <h1 class="display-6 font-weight-bold wow fadeIn" data-wow-delay="0.3s">{{ cityWithCategory.category.slider.title }}</h1>
                                        <hr class="hr-light wow fadeIn w-50" data-wow-delay="0.3s">
                                    </li>
                                    <li>
                                        <h3>{{ cityWithCategory.category.slider.description }}</h3>
                                    </li>
                                    <li>
                                        {% include 'home/contact_index_normal.html.twig' %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Mask -->
                    </div>
                {% else %}
                    {% for s in global.slider %}
                        <div class="carousel-item {% if loop.index == 1 %}active{% endif %}">
                            <!-- Mask -->
                            <div class="view">
                                <div
                                        class="h-100 d-flex justify-content-center align-items-center mask rgba-black-light white-text text-center">
                                    <ul class="list-unstyled animated fadeInUp col-md-12">
                                        <li>
                                            <h1 class="display-6 font-weight-bold wow fadeIn" data-wow-delay="0.3s">{{ s.title }}</h1>
                                            <hr class="hr-light wow fadeIn w-50" data-wow-delay="0.3s">
                                        </li>
                                        <li>
                                            <h3>{{ s.description }}</h3>
                                        </li>
                                        <li>
                                            {% include 'home/contact_index_normal.html.twig' %}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!-- Mask -->
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <!-- Slides -->

            <!-- Controls -->
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            <!-- Controls -->
        </div>
        <!-- Carousel Wrapper -->
    {% endif %}

</header>
<!-- Navigation & Intro -->